- name: change hostname 
  hosts: valerian
  become: yes
  become_user: root   # like sudo suhost-
  
  vars_files:
    - "{{ipack}}valerian/playbooks/vars//valerian-server-common-vars.yaml"
    
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600   # reuse cache if < 1h old

    - name: Install required packages
      ansible.builtin.apt:
        name:  "{{required_packages}}"
        state: present
