- name: change hostname 
  hosts: valerian
  become: yes
  become_user: root   # like sudo suhost-
  
  vars_files:
    - "{{ipack}}valerian/playbooks/vars//valerian-server-common-vars.yaml"
    - "{{ customer_data_dir }}common/domain-common-vars.yaml"
  vars: 
    tmplts: "templates/onsite-prerequisite/"
 
 
  tasks:
# Create insecure registry file

    - name: Create insecure registry file
      template:
        src: '{{tmplts}}daemon.json.j2'
        dest: '/etc/docker/daemon.json'

    - name: reload systemctl services
      command: systemctl daemon-reload

    - name: restart docker service
      service:
        name: docker.service
        state: restarted
        enabled: yes
