consul_templates_home_dir: '/usr/local/bin'
consul_templates_opt_dir: '/v/opt/consul-templates'
consul_templates_service_file: '/etc/systemd/system/consul-templates.service'
consul_template_log_file: '/v/opt/consul-templates/logs/consul_log.log'
zip_src: '../../packages/consul-template_0.23.0_linux_amd64.zip'
unzip_dest: '/usr/local/bin'
action_items_conf_folder: '/v/opt/action_items/config/'
simba_conf_folder: '/v/opt/simba/config/'
redis_conf_folder: '/v/opt/redis/conf/'
siddhi_apps_folder: '/v/opt/siddhi/apps/'
viisights_app_folder: '/v/opt/viisights/app/'
risconnect_app_folder: '/v/opt/risconnect/app/'
anyvision_app_folder: '/v/opt/anyvision/app/'
okazas_app_folder: '/v/opt/okazas/app/'
clio_app_folder: '/v/opt/clio/app/'
itto_app_folder: '/v/opt/itto/app/'
mikado_app_folder: '/v/opt/mikado/app/'
davantis_app_folder: '/v/opt/davantis/app/'
united_app_folder: '/v/opt/united/app/'
gallagher_app_folder: '/v/opt/gallagher/app/'
cawamo_app_folder: '/v/opt/cawamo/app/'
findface_app_folder: '/v/opt/findface/app/'
urbandigital_app_folder: '/v/opt/urbandigital/app'
nelysis_app_folder: '/v/opt/nelysis/app'
agrolan_app_folder: '/v/opt/agrolan/app'
arad_app_folder: '/v/opt/arad/app'
aqua_app_folder: '/v/opt/aqua/app'
agam_app_folder: '/v/opt/agam/app'
simplex_app_folder: '/v/opt/simplex/app'
netiot_app_folder: '/v/opt/netiot/app'
xls_app_folder: '/v/opt/xls/app'
magos_app_folder: '/v/opt/magos/app'
suprema_app_folder: '/v/opt/suprema/app'
desigo_app_folder: '/v/opt/desigo/app'
tyco_app_folder: '/v/opt/tyco/app'
swilco_app_folder: '/v/opt/swilco/app'
g1_app_folder: '/v/opt/g1/app'
xhuma_app_folder: '/v/opt/xhuma/app'
zabbix_app_folder: '/v/opt/zabbix/app'
zabbix_alertscripts_folder: '/v/opt/zabbix/alertscripts/'
zabbix_mibs_folder: '/v/opt/zabbix/share/snmp/mibs/'
logstash_conf_folder: '/v/opt/logstash/config/'
logstash_plugin_folder: '/v/opt/logstash/lib/pluginmanager/'
logstash_pipeline_examples_folder: '/v/opt/logstash/pipeline_examples/'
logstash_pipeline_folder: '/v/opt/logstash/pipeline/'
logstash_driver_folder: '/v/opt/logstash/driver/'
superset_config_folder: '/v/opt/superset/config/'
grafana_conf_folder: '/v/opt/grafana/conf/'
jasper_folder: '/v/opt/jasperserver'
mssql_jdbc_src: '../../packages/{{ mssql_jdbc_jar }}'
mssql_jdbc_jar: 'mssql-jdbc-7.4.1.jre8.jar'
mssql_jdbc_dest: '{{jasper_folder}}/datasources/'
jasper_lib_folder: '{{jasper_folder}}/WEB-INF/lib/'
jasper_esapi_folder: '{{jasper_folder}}/WEB-INF/classes/esapi/'
jasper_webinf_folder: '{{jasper_folder}}/WEB-INF/'
pulsar_conf_folder: '/v/opt/pulsar/config/'

pg_jar_src: '../../packages/{{ pg_jar }}'
pg_jar: 'postgresql-42.2.19.jar'
pg_jar_dest: '{{jasper_folder}}/datasources/'

minio_data_folder: '/root/minio/data'
