windows_install_dir: 'C:\mer\WindowsInstallation\'
apppools_file: 'C:\mer\WindowsInstallation\apppools.xml'
web_config_file: 'C:\SMNG\Server\Web\Web.config'
gis_web_config_file: 'C:\SMNG\GISServer\Web\Web.config'
notification_web_config_file: 'C:\SMNG\Notification\Web.config'
minio_shared_directory: 'C:\minio'
import_pools_script_path: 'C:\mer\WindowsInstallation\ImportIISApplicationPool.ps1'
smng_data_pool: 'SMNG.DATA.ServerApplicationPool'
web_sites_json: 'sites.json'
import_web_sites_script_file: 'IIS-WebSites-Export-Import.ps1'
